services:
  database:
    image: mariadb:latest
    container_name: mariadb-container
    environment:
      MYSQL_ROOT_PASSWORD: DB_PASSWORD
      MYSQL_DATABASE: timetable-database  
    ports:
      - "3306:3306"  # Expose the database on port 3306
    networks:
      - timetable-network
    volumes:
      - "datasave:/var/lib/mysql"  # Volume for persistent data storage
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  api:
    build:
      context: ./src/backend # Path to the Dockerfile of the api-image
      dockerfile: Dockerfile
    container_name: api-container
    ports:
      - "8000:8000"  # Expose the API on port 8000
    networks:
      - timetable-network
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - 3000:3000
    networks:
      - timetable-network

networks:
  timetable-network:

volumes:
  datasave: 